import pytest
from spectools.utils import *
import astropy.io.fits as pf
from specutils import Spectrum1D
from numpy.testing import assert_array_equal

def header(filename):
    return pf.getheader(filename)

def test_get_keyword():
    filename = 'data/s1_2016-10-12T04-33-07_ext.fits'
    keyword = get_keyword(header(filename), 'IMFORM')
    assert keyword == 'FITS'

def test_wavelength():
    """Wavelength generated by specutils.Spectrum1D"""
    filename = 'data/hermes_spec.fits'
    reference_wavelength = Spectrum1D.read(filename).spectral_axis.value
    wavelength_from_function = wavelength(header(filename))
    assert_array_equal(wavelength_from_function,reference_wavelength)
